# Generated by Django 5.2.8 on 2025-11-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('productid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('rating', models.FloatField()),
                ('Deldate', models.DateTimeField()),
                ('company', models.CharField(max_length=20)),
                ('stock', models.CharField(max_length=20)),
            ],
        ),
    ]
